config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  resources :cuisines

  resources :restaurants do
    resources :reviews
  end

  # root 'restaurants#index', as: 'restaurant_index'
  root to: 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id                :integer          not null, primary key
#  name              :string
#  address           :string
#  max_delivery_time :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  tenbis            :boolean
#  cuisine_id        :integer
#

class Restaurant < ApplicationRecord

  # A restaurant has many associated reviews.
  # Each review contains a reference to its restaurant's ID
  # The existence of reviews is dependent on the existence of the restaurant.
  has_many :reviews
  belongs_to :cuisine

  # Validates that the text fields all contain something
  validates_presence_of :name,
                        :cuisine,
                        :address,
                        :max_delivery_time

  validates :tenbis, inclusion: [true, false]

  # Validates that the maximum delivery time is between 0-100 minutes.
  validates :max_delivery_time, numericality: {greater_than_or_equal_to: 0}

  def get_rating
    reviews.size == 0 ? -1 : reviews.average(:rating).round
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
     @restaurants = Restaurant.order(:name)
     render json: @restaurants, each_serializer: RestaurantSerializer
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show; end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit; end

  # POST /restaurants
  # POST /restaurants.json
  def create
    Rails.logger.info restaurant_params
    cuisine = Cuisine.find(restaurant_params[:cuisine])
    updated_restaurant_params = restaurant_params
    updated_restaurant_params[:cuisine] = cuisine
    @restaurant = Restaurant.new(updated_restaurant_params)
    Rails.logger.info "Created new restaurant"

    respond_to do |format|
      if @restaurant.save
        Rails.logger.info "Saved restaurant"
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        Rails.logger.info "Didn't save restaurant"
        Rails.logger.info @restaurant.errors
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :cuisine, :tenbis, :address, :max_delivery_time)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :restaurant_name %>
  </div>

  <div class="field">
    <%= form.label :cuisine %>
    <%= form.text_field :cuisine, id: :restaurant_cuisine %>
  </div>

  <div class="field">
    <%= form.label :tenbis %>
    <%= form.number_field :tenbis, id: :restaurant_tenbis %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :restaurant_address %>
  </div>

  <div class="field">
    <%= form.label :max_delivery_time %>
    <%= form.number_field :max_delivery_time, id: :restaurant_max_delivery_time %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :restaurant_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cuisine</th>
      <th>10bis</th>
      <th>Address</th>
      <th>Max delivery time</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.cuisine.name %></td>
        <td><%= restaurant.tenbis %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.max_delivery_time %></td>
        <td><%= restaurant.get_rating %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Add a review', new_restaurant_review_url(restaurant_id: restaurant) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @restaurant.cuisine.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @restaurant.get_rating %>
</p>

<p>
  <strong>Tenbis:</strong>
  <%= @restaurant.tenbis %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Max delivery time:</strong>
  <%= @restaurant.max_delivery_time %>
</p>

<%= link_to 'Reviews', restaurant_reviews_path(@restaurant)%> |
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>