config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  resources :cuisines

  resources :restaurants do
    resources :reviews
  end

  # root 'restaurants#index', as: 'restaurant_index'
  root to: 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = restaurant.reviews

    respond_to do |format|
      format.html #index.html.erb
    end

  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    restaurant = Restaurant.find(params[:restaurant_id])

    @review = restaurant.reviews.find(params[:id])

    respond_to do |format|
      format.html #show.html.erb
    end

  end

  # GET /reviews/new
  def new
    restaurant = Restaurant.find(params[:restaurant_id])

    @review = restaurant.reviews.build

    respond_to do |format|
      format.html #new.html.erb
    end

  end

  # GET /reviews/1/edit
  def edit
    restaurant = Restaurant.find(params[:restaurant_id])
    @review = restaurant.reviews.find(params[:id])

  end

  # POST /reviews
  # POST /reviews.json
  def create
    restaurant = Restaurant.find(params[:restaurant_id])
    params.permit!
    @review = restaurant.reviews.create(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to([@review.restaurant, @review], notice: 'Review was successfully created.')}
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :action => "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    restaurant = Restaurant.find(params[:restaurant_id])
    @review = restaurant.reviews.find(params[:id])

    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to([@review.restaurant, @review], notice: 'Review was successfully updated.')}
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :action => "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    restaurant = Restaurant.find(params[:restaurant_id])
    @review = restaurant.reviews.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to(restaurant_reviews_url) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:restaurant_id, :reviewer_name, :rating, :comment)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@review.restaurant, @review]) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :reviewer_name %>
    <%= form.text_field :reviewer_name %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :review_rating %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :review_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', [@review.restaurant, @review] %> |
<%= link_to 'Back', restaurant_reviews_path(@review.restaurant) %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Reviewer name</th>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.reviewer_name %></td>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>

        <td><%= link_to 'Show', [review.restaurant, review] %></td>
        <td><%= link_to 'Edit', edit_restaurant_review_path(review.restaurant, review) %></td>
        <td><%= link_to 'Destroy', [review.restaurant, review], :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_restaurant_review_path %>

<%= link_to 'Back to restaurants', restaurants_path %>
<%= link_to 'Back', :back %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', restaurant_reviews_path(@review.restaurant) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reviewer:</strong>
  <%= @review.reviewer_name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<%= link_to 'Edit', edit_restaurant_review_path(@review.restaurant, @review) %> |
<%= link_to 'Back', restaurant_reviews_path(@review.restaurant) %>